import { Poppins } from "next/font/google";
import "normalize.css";
import AuthProvider from "./context/AuthContext";
import { Footer, Nav } from "./layouts";
const inter = Poppins({
  weight: ["300", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Sneak",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav />
        <AuthProvider>
          <main>{children}</main>
        </AuthProvider>
        <Footer />
      </body>
    </html>
  );
}
